
SNL_MODEL_CHECKPOINT_PATH=/storage/vladi/snl/optimize_and_reduce/checkpoints/resnet18_tiny_imagenet_150000.pth
TEACHER_MODEL_CHECKPOINT_PATH=/storage/vladi/snl/optimize_and_reduce/checkpoints/resnet18_tiny_imagenet.pth


REDUCE_THRESHOLD=0.3
STEP_REDUCE=100
RANDOM_TRIES=50
RELU_TARGET=99600


OUTPUT_DIR=/storage/vladi/snl/optimize_and_reduce/outputs/TINY_IMAGENET_RELU_TARGET_$RELU_TARGET-REDUCE_THRESHOLD_$REDUCE_THRESHOLD-RANDOM_TRIES_$RANDOM_TRIES-STEP_REDUCE_$STEP_REDUCE
